services:
  db:
    image: postgres:14
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - nt_db_volume:/var/lib/postgresql/data
    ports:
      - '54321:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - TZ=UTC
    # This helps avoid 'pq: could not resize shared memory segment' error that sometimes happens under load. It seems
    # to be common in docker environments because it by default limits shared memory to 64MB. Thanks to
    # https://stackoverflow.com/a/56754077/6117745
    shm_size: 512mb

  dev:
    build:
      context: .
      target: node_base
    ports:
      - '8044:8044'
      - '9044:9044'
    volumes:
      - .:/home
    environment:
      - TZ=UTC
    depends_on:
      - db

volumes:
  nt_db_volume:
  nt_notused:
