/**
 * @module UserRoleHelper
 */

import { generateUUID } from '../../../app/lib/general.lib.js'
import { generateUserId } from './user.helper.js'
import { select as RoleSelector } from './role.helper.js'
import UserRoleModel from '../../../app/models/user-role.model.js'

/**
 * Add a new user role
 *
 * If no `data` is provided, default values will be used. These are
 *
 * - `userId` - [randomly generated - 100001]
 * - `roleId` - [randomly selected UUID from roles]
 *
 * @param {object} [data] - Any data you want to use instead of the defaults used here or in the database
 *
 * @returns {Promise<module:UserRoleModel>} The instance of the newly created record
 */
export async function add(data = {}) {
  const insertData = defaults(data)

  return UserRoleModel.query()
    .insert({ ...insertData })
    .returning('*')
}

/**
 * Returns the defaults used
 *
 * It will override or append to them any data provided. Mainly used by the `add()` method, we make it available
 * for use in tests to avoid having to duplicate values.
 *
 * @param {object} [data] - Any data you want to use instead of the defaults used here or in the database
 *
 * @returns {object} - Returns the set defaults with the override data spread
 */
export function defaults(data = {}) {
  const { id: roleId } = RoleSelector()

  const defaults = {
    // We create a random uuid as the id is NOT generated by the db, unlike most other tables
    id: generateUUID(),
    userId: generateUserId(),
    roleId
  }

  return {
    ...defaults,
    ...data
  }
}
